version: "3.9"

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: grsu
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: grsudb

  fastapi_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://grsu:1111@db:5432/grsudb
    volumes:
      - ./backend:/app
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
