"""rename is_present to detected

Revision ID: 3e96c5d9ee97
Revises: 867fcc03e921
Create Date: 2025-05-08 01:52:58.676354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e96c5d9ee97'
down_revision: Union[str, None] = '867fcc03e921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('detected', sa.Boolean(), nullable=False))
    op.drop_column('attendance', 'is_present')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('is_present', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('attendance', 'detected')
    # ### end Alembic commands ###
