"""add students_values

Revision ID: 537110d68d40
Revises: 908e8e4f51ee
Create Date: 2025-05-08 00:55:47.524971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '537110d68d40'
down_revision: Union[str, None] = '908e8e4f51ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('students_value', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'students_value')
    # ### end Alembic commands ###
