"""Add teacher_id and date to Lesson

Revision ID: 7b2b3e74e076
Revises: db2dee334ca8
Create Date: 2025-05-06 23:05:05.291205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2b3e74e076'
down_revision: Union[str, None] = 'db2dee334ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.alter_column('lessons', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_foreign_key(None, 'lessons', 'users', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.alter_column('lessons', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('lessons', 'teacher_id')
    # ### end Alembic commands ###
